import enum


class CheckExceptionEnum(enum.Enum):
    OK = 'OK'
    VARIABLE_REQUIRED = 'VARIABLE_REQUIRED'
    DISCONNECTED_SOCKET = 'DISCONNECTED_SOCKET'
    UNCHECKED_SOCKET = 'UNCHECKED_SOCKET'
    INFINITIVE_CYCLE = 'INFINITIVE_CYCLE'
